### ISSUE TITLE
What units should be default?

### ISSUE THREAD

**Issue by jth41** [jth41/sbca-data-standard#2]
Should we use the Imperial or Metric system and which unit for distance, etc.

**Comment by JurenVekta** [comment]
Metric is easier from a programming standpoint because it more easily stores as a decimal number.  Metric is also more internationally accepted for customers in Canada, Australia, etc.

**Comment by jth41** [comment]
@JurenVekta Do you know what the metric standard unit is when describing dimensions for components, members, bearings, etc. in Canada, Australia, etc. (cm? m?)

**Comment by JurenVekta** [comment]
Vekta Advanced Automation is originally headquartered in Australia.  All
our software runs on millimeters for measurements.  I believe the
Australian customers are mostly using Mitek software for design and sending
jobs, which also delivers the measurements in mm.  This way you end up
dealing with fewer decimal numbers while keeping precision pretty good.

Note that to be accurate to the 1/16th inch (1.5875mm), you still need four
decimal places.  To be accurate to 1/32nd inch (0.79375mm), you will need 5
decimal places.

Kind Regards,

Juren Raske
Automation/Software Engineer

<https://vekta.com.au>

Address

1601 67th Ave N
Ste A Brooklyn Center
MN 55430 USA

Web

vektausa.com

Phone

+1 (612) 564-2933 (mobile)

+1 (763) 566-0781 (main)

Email

juren@vektausa.com
juren@vekta.com.au

This message and its attachments contain confidential information. If you
are not the intended recipient, you are strictly prohibited to disclose,
copy, distribute or take any action in reliance on the contents of this
information. E-mail transmission cannot be guaranteed to be secure or
error-free, as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.
If verification is required, please request a hard-copy version.

🌎 Be green, keep it on the screen.

**Comment by jth41** [comment]
@JurenVekta Sorry for taking so long for a response. This is great information. I'm really glad to have some of you guys who have more international experience chiming in. I'm gonna leave this issue open and wait for others to jump into the discussion as they find this repo.

**Comment by ChrisGouldIs** [comment]
Mathematically, I certainly prefer Metric. However, in attempting to keep this human readable, and knowing that most of our users recognize decimal inches intuitively, I'd probably vote Imperial. However, whichever way we opt, I'd strongly vote to include the units as well, just in case.

**Comment by jth41** [comment]
I Added Enums to allow for specifying Units throughout the file in Pull Request #6. Current options are Millimeters and Inches. Feel free to make a pull request with changes if you would like to include more units, etc.

**Comment by jth41** [comment]
Resolved in Pull Request #6
